Milestone 1:Portfolio project
ismayito/Portfolio-project pull request #1
Opened 2022-10-27 11:17 UTC by ismayito

in this milestone ;
I created the header section and headline of my portfolio website for the mobile view

2022-10-27 11:57 UTC, BregornOriginal requested changes
Hi @ismayito , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

❌ Linters are not passing

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-27 14:41 UTC, anagudelogu requested changes
Hi @ismayito , 

Great job working on the toolbar and headline sections of your future portfolio! 🍾 🎆 
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif"/>

## Highlights
✅ Good responsive design. 💯
✅ Great PR title. 🥇 
✅ Great usage of GitHub flow. 👍🏼  

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 14:41 UTC, anagudelogu commented on index.html
> +        <header class="header">
- [ ] Let's remove this `<header>` tag and implement it in the previous request! 💯

2022-10-27 14:41 UTC, anagudelogu commented on index.html
> +                            </ul>
- [ ] Great use of a list element to wrap the list of social media icons! 🥇 However, remember that to make this tag semantically correct, it should wrap the list items inside `<li>` tags. This will provide better information to the browser and screen readers for people that rely on them. Let's make the web more accessible! Kindly fix this. 🛠️

2022-10-27 14:41 UTC, anagudelogu commented on style.css
> +}
- [ ] Try to stick as much as possible to the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27). 🎨 These includes color, fonts, font-size, spacing, etc. Remember that knowing how to follow a given design is a very important skill in the industry as a front-end developer! Let's fix the font size and the spacing between elements! 🛠️ 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/198318279-d9c00eca-d30c-42c7-9784-dbf83f02f62a.png) | ![image](https://user-images.githubusercontent.com/77069011/198318058-eb1e66cb-9ffa-406d-8283-6ea405b66df5.png) |

2022-10-27 18:23 UTC, aimalamiri requested changes
Hi @ismayito, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191356050-93e2eb80-7c05-4749-92f7-8925a1fa9386.gif)


 ## Highlights

- The header section is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 18:23 UTC, aimalamiri commented on style.css
> +  font-size: 40px;
It looks great 👌but you can make it even better by following the original design. The size in the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) template is 56px, please make sure to update your font-size.

2022-10-27 18:23 UTC, aimalamiri commented on index.html
> +    </header>
It's almost the same, but you can make it completely the same if you remove the extra space from the top. Kindly make sure to fix it.

![image](https://user-images.githubusercontent.com/34779928/198368641-04e72d48-1cdb-45bf-86e2-dfa27a9f10c1.png)

2022-10-28 03:08 UTC, Gopxfs approved these changes
# 🟢 STATUS: APPROVED 🟢

## Hello @ismayito 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 07:24 UTC, merged